import Component from 'vue-class-component';

import AppMapDetailsBase from '@/components/AppMapDetailsBase';
import ObjectInfo from '@/components/ObjectInfo';
import { MapMarkerCave } from '@/MapMarker';
import {
  MapMgr,
  ObjectMinData,
} from '@/services/MapMgr';

@Component({
  components: {
    ObjectInfo,
  },
})
export default class AppMapDetailsCave extends AppMapDetailsBase<MapMarkerCave> {
  private locationId = '';
  private pos: number[] = [];
  private objs: ObjectMinData[] = [];
  private shrines: ObjectMinData[] = [];
  private tboxObjs: ObjectMinData[] = [];
  private bubbulfrogObjs: ObjectMinData[] = [];
  private enemies: ObjectMinData[] = [];
  private npcs: ObjectMinData[] = [];
  private hardSediments: ObjectMinData[] = [];
  private wallCracks: ObjectMinData[] = [];
  private vines: ObjectMinData[] = [];
  private sandPiles: ObjectMinData[] = [];
  private iceWalls: ObjectMinData[] = [];
  private thinIce: ObjectMinData[] = [];
  private checked: { [key: string]: boolean } = {};

  protected init() {
    this.locationId = this.marker.data.lm.getMessageId();
    this.pos = this.marker.data.lm.getXYZ();
    this.objs = [];
    this.shrines = [];
    this.tboxObjs = [];
    this.bubbulfrogObjs = [];
    this.enemies = [];
    this.npcs = [];
    this.hardSediments = [];
    this.wallCracks = [];
    this.vines = [];
    this.sandPiles = [];
    this.iceWalls = [];
    this.thinIce = [];

    const markerObj = (this.marker.data as any).obj as ObjectMinData | undefined;
    if (markerObj) {
      this.objs = [markerObj];
      this.updateChecked(this.objs);
    }

    const escaped = this.locationId.replace(/"/g, '\\"');
    // Some cave objects have non-cave map_name but carry the cave id in
    // Dynamic.LocationName. Query both the map path and the bare location
    // token, then deduplicate so every category picks them up.
    const caveQuery = (filter: string) => {
      const mapQ = `map:"MainField/Cave__${escaped}*" ${filter}`;
      const locQ = `${escaped} ${filter}`;
      return Promise.all([
        MapMgr.getInstance().getObjs('MainField', '', mapQ),
        MapMgr.getInstance().getObjs('MainField', '', locQ),
      ]).then(([a, b]) => {
        const seen = new Set<string>();
        const out: ObjectMinData[] = [];
        for (const obj of a.concat(b)) {
          if (!seen.has(obj.hash_id)) {
            seen.add(obj.hash_id);
            out.push(obj);
          }
        }
        return out;
      });
    };

    const assign = (target: string, data: ObjectMinData[]) => {
      (this as any)[target] = data;
      this.updateChecked(data);
    };

    caveQuery('BGM_Shrine').then(d => assign('shrines', d));
    caveQuery('actor:^"TBox_" NOT actor:_Opened NOT actor:_CanNotOpen').then(d => assign('tboxObjs', d));
    caveQuery('Bubbulfrog').then(d => assign('bubbulfrogObjs', d));
    caveQuery('actor:^"Enemy_" NOT Bubbulfrog').then(d => assign('enemies', d));
    caveQuery('AND (actor:npc* NOT korok* NOT npc_craft* NOT footsoldier NOT blademaster NOT npc_minus* NOT NpcGarden* OR npc_korokfly* OR HorseAssociation* OR actor:subchallnpc*)').then(d => assign('npcs', d));
    caveQuery('actor:AutoGenerateDestructibleActor*').then(d => assign('hardSediments', d));
    caveQuery('AND (actor:WallCrack OR actor:RockBroken) NOT actor:TwnObj_HyruleCastleObject_Wallcrack_After_A_01 NOT Obj_RockBroken_Miasma_A_02 NOT DmObj').then(d => assign('wallCracks', d));
    caveQuery('actor:TreeSkyLiana').then(d => assign('vines', d));
    caveQuery('DgnObj_ElectricFragmentsSand_A_03').then(d => assign('sandPiles', d));
    caveQuery('actor:IceWall* NOT Rito').then(d => assign('iceWalls', d));
    caveQuery('actor:ThinFilmBoard').then(d => assign('thinIce', d));
  }

  private mounted() {
    this.$on('AppMap:update-search-markers', (args: any) => {
      if (args && args.hash_id) {
        this.$set(this.checked, args.hash_id, !this.checked[args.hash_id]);
        const appMap: any = this.$parent;
        if (appMap && typeof appMap.$emit === 'function') {
          appMap.$emit('AppMap:update-search-markers', args);
        }
      }
    });
  }

  private updateChecked(objs: ObjectMinData[]) {
    const appMap: any = this.$parent;
    for (const obj of objs) {
      if (this.checked[obj.hash_id] === undefined) {
        const value = appMap && appMap.checklists
          ? appMap.checklists.isMarked(obj.hash_id)
          : false;
        this.$set(this.checked, obj.hash_id, value);
      }
    }
  }

  private isChecked(obj: ObjectMinData) {
    return !!this.checked[obj.hash_id];
  }

  private openShrineDetails(obj: ObjectMinData) {
    const appMap: any = this.$parent;
    if (appMap && typeof appMap.$emit === 'function') {
      appMap.$emit('AppMap:open-shrine-from-bgm', obj);
    }
  }
}
